import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import {
	flexRender,
	type Row,
	type Table,
	type RowData,
} from "@tanstack/react-table";
import { ArrowLeft, ArrowRight, ArrowUp, ArrowDown } from "lucide-react";
import { useEffect } from "react";
import { useTranslation } from "react-i18next";

//https://tanstack.com/table/v8/docs/guide/pagination - Pagination tutorial

const pageSizeOptions = [5, 10, 20, 50, 100, 6122];

declare module "@tanstack/react-table" {
	interface ColumnMeta<TData extends RowData, TValue> {
		tooltip?: (data: TData) => string;
	}
}

export default function AdminTable<T>({
	table,
	onRowClick,
	rowClassName,
	getRowProps,
	defaultPageSize,
}: {
	table: Table<T>;
	onRowClick?: (row: Row<T>) => void;
	rowClassName?: (row: Row<T>) => string;
	getRowProps?: (row: Row<T>) => React.HTMLProps<HTMLTableRowElement>;
	defaultPageSize?: number;
}) {
	const { pageIndex } = table.getState().pagination;
	const pageCount = table.getPageCount();
	const { t } = useTranslation("admin");

	// Set default page size if provided and not already set
	// biome-ignore lint/correctness/useExhaustiveDependencies: we don't want to run this on every table state change
	useEffect(() => {
		if (
			defaultPageSize &&
			table.getState().pagination.pageSize !== defaultPageSize
		) {
			table.setPageSize(defaultPageSize);
		}
		// Only run on mount or when defaultPageSize changes
	}, [defaultPageSize]);

	return (
		<div className="flex flex-col w-full">
			<div className="overflow-x-auto">
				<table className="table-auto border border-table-border w-full border-collapse">
					<thead>
						{table.getHeaderGroups().map((headerGroup) => (
							<tr key={headerGroup.id}>
								{headerGroup.headers.map((header) => {
									const size = header.column.columnDef.size;
									const isShrink = size === 0;

									return (
										<th
											key={header.id}
											className="px-2.5 py-2 text-left border-r border-table-border last:border-r-0"
											colSpan={header.colSpan}
											style={{
												width: isShrink ? "1%" : header.column.getSize(),
											}}
											aria-sort={
												header.column.getIsSorted()
													? header.column.getIsSorted() === "asc"
														? "ascending"
														: "descending"
													: "none"
											}
										>
											{header.isPlaceholder ? null : (
												<div
													className={cn(
														"flex items-center",
														header.column.getCanSort() &&
															"cursor-pointer select-none",
													)}
													onClick={header.column.getToggleSortingHandler()}
												>
													{flexRender(
														header.column.columnDef.header,
														header.getContext(),
													)}
													{header.column.getIsSorted() &&
														(header.column.getIsSorted() === "asc" ? (
															<ArrowDown className="ml-1 w-4 h-4" />
														) : (
															<ArrowUp className="ml-1 w-4 h-4" />
														))}
												</div>
											)}
										</th>
									);
								})}
							</tr>
						))}
					</thead>
					<tbody>
						{table.getRowModel().rows.map((row) => {
							const extraProps = getRowProps?.(row) ?? {};
							return (
								<tr
									key={row.id}
									onClick={() => onRowClick?.(row)}
									className={cn(
										"border-t hover:bg-gray-50 dark:hover:bg-gray-800",
										rowClassName?.(row),
										extraProps.className,
										onRowClick && "cursor-pointer",
									)}
									{...extraProps}
								>
									{row.getVisibleCells().map((cell) => {
										const { column } = cell;
										const { size, minSize, maxSize } = column.columnDef;

										// 0 is our "shrink-to-fit" flag
										const isShrink = size === 0;

										// Tooltip Logic
										// Tries to automagically generate a tooltip from cell value
										// if not specified in column meta
										const cellDef = column.columnDef.cell;
										let tooltipValue: string | undefined;
										const tooltip = column.columnDef.meta?.tooltip;
										if (!tooltip) {
											if (typeof cellDef === "function") {
												// If cell generated by function
												const result = cellDef(cell.getContext());
												if (
													typeof result === "string" ||
													typeof result === "number"
												) {
													tooltipValue = String(result);
												}
											}
											if (!tooltipValue) {
												const nativeVal = cell.renderValue();
												if (
													typeof nativeVal === "string" || // If cell defined as string or number
													typeof nativeVal === "number"
												) {
													tooltipValue = String(nativeVal);
												}
											}
										} else {
											tooltipValue = tooltip(row.original);
										}
										return (
											<td
												key={cell.id}
												className={cn(
													"px-2.5 py-2 border-r border-table-border last:border-r-0",
													// w-[calc(...)] taps into the Tailwind spacing theme directly
													isShrink
														? "w-[1%]"
														: "w-[calc(--spacing(1)*var(--size))] max-w-0",
												)}
												style={
													{
														"--size": size,
														"--min":
															isShrink && (minSize ?? 20) <= 20
																? "auto"
																: minSize,
														"--max": maxSize,
													} as React.CSSProperties
												}
											>
												<div
													className={cn(
														"min-w-[calc(--spacing(1)*var(--min))]",
														"max-w-[calc(--spacing(1)*var(--max))]",
														isShrink ? "w-max" : "truncate w-full",
													)}
													title={tooltipValue}
												>
													{flexRender(column.columnDef.cell, cell.getContext())}
												</div>
											</td>
										);
									})}
								</tr>
							);
						})}
					</tbody>
					<tfoot>
						{table.getFooterGroups().map((footerGroup) => (
							<tr key={footerGroup.id}>
								{footerGroup.headers.map((header) => (
									<th
										key={header.id}
										className="px-4 py-2 text-left border-r border-table-border last:border-r-0 truncate"
										style={{ width: header.column.getSize() }}
									>
										{header.isPlaceholder
											? null
											: flexRender(
													header.column.columnDef.footer,
													header.getContext(),
												)}
									</th>
								))}
							</tr>
						))}
					</tfoot>
				</table>
			</div>
			<div className="mt-4 m-5 flex justify-end space-x-1">
				<Button
					className="px-4 py-2 text-white rounded"
					onClick={() => table.previousPage()}
					disabled={!table.getCanPreviousPage()}
				>
					<ArrowLeft />
				</Button>
				<Button
					variant="ghost" // Optional: Choose a variant that suits your design
					className="px-4 py-2 text-gray-700 rounded cursor-default"
					disabled
				>
					{pageIndex + 1}/{pageCount}
				</Button>
				<Button
					className="px-4 py-2 text-white rounded"
					onClick={() => table.nextPage()}
					disabled={!table.getCanNextPage()}
				>
					<ArrowRight />
				</Button>
				<select
					value={table.getState().pagination.pageSize}
					onChange={(e) => {
						table.setPageSize(Number(e.target.value));
					}}
					className="ml-4 px-2 py-1 border rounded"
				>
					{pageSizeOptions.map((size) => (
						<option key={size} value={size}>
							{t("show")} {size}
						</option>
					))}
				</select>
			</div>
		</div>
	);
}
