name: Push to production

on:
  workflow_dispatch:

permissions:
  contents: write  

jobs:
  deploy-to-stage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare stage branch
        run: |
          # Set commit identity
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Fetch and reset a local 'stage' to main
          git fetch origin main
          git checkout -B production origin/main

          # Ensure there's a change even if main==production
          echo " " >> README.md
          git add README.md

          # Commit with a consistent message
          git commit -m "chore: trigger production workflow [ci skip]"

      - name: Push to stage
        run: |
          git push origin production --force